// Code generated by hertz generator.

package product

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/douyin-shop/douyin-shop/app/frontend/biz/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listproductsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchproductsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addproductMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyTokenMiddleware(),
		middleware.GetCasbinMiddleware().RequiresPermissions("/product:edit"),
	}
}

func _deleteproductMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyTokenMiddleware(),
		middleware.GetCasbinMiddleware().RequiresPermissions("/product:edit"),
	}
}

func _updateproductMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyTokenMiddleware(),
		middleware.GetCasbinMiddleware().RequiresPermissions("/product:edit"),
	}
}
