// Code generated by hertz generator.

package checkout

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/douyin-shop/douyin-shop/app/frontend/biz/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkoutMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyTokenMiddleware(),
		middleware.GetCasbinMiddleware().RequiresPermissions("/checkout:*"),
	}
}
