// Code generated by hertz generator.

package cart

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/douyin-shop/douyin-shop/app/frontend/biz/middleware"
)

func rootMw() []app.HandlerFunc {
	return nil
}

func _addcartitemMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.VerifyTokenMiddleware(),
		middleware.GetCasbinMiddleware().RequiresPermissions("/cart:*"),
	}
}

func _getcartMw() []app.HandlerFunc {
	return nil
}

func _cartMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.VerifyTokenMiddleware(),
		middleware.GetCasbinMiddleware().RequiresPermissions("/cart:*"),
	}
}
