// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	cart "github.com/douyin-shop/douyin-shop/app/frontend/biz/router/cart"
	user "github.com/douyin-shop/douyin-shop/app/frontend/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	cart.Register(r)

	user.Register(r)
}
