GET http://localhost:8080/cart/get_cart
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc5MDU4MjMsInVzZXJfaWQiOjF9.UFoL-XTHXfpT1ZVN1UcU-joB13oRMTH-5g-zfIAXYao