
POST http://localhost:8080/login
Content-Type: application/json

{
  "email":"wyz17601402786@gmail.com",
  "password":"123456"
}

###
POST http://localhost:8080/register
Content-Type: application/json


{
  "email":"wyz17601402786@gmail.com",
  "password":"123456"
}

###
GET http://localhost:8080/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzgzMzcyNzQsInVzZXJfaWQiOjJ9.kKsLwiLhk_izeAZjH5pH44q3FzuVHxAj3VUuUZEjFbc

{
  
}