// Code generated by hertz generator.

package order

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/douyin-shop/douyin-shop/app/frontend/biz/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.VerifyTokenMiddleware(),
		middleware.GetCasbinMiddleware().RequiresPermissions("/order:*"),
	}
}

func _listorderMw() []app.HandlerFunc {
	// your code...
	return nil
}
