name: Deploy Go Service

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build Submodule A
        run: go build -o main-a ./submoduleA

      - name: Build Submodule B
        run: go build -o main-b ./submoduleB

      - name: Deploy Submodule A
        run: |
          scp -o StrictHostKeyChecking=no main-a ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/path/to/appA
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "nohup /path/to/appA/main-a > /path/to/appA/appA.log 2>&1 &"

      - name: Deploy Submodule B
        run: |
          scp -o StrictHostKeyChecking=no main-b ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/path/to/appB
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "nohup /path/to/appB/main-b > /path/to/appB/appB.log 2>&1 &"
